# Transformers

To understand transformers from scratch, refer [this]('http://www.peterbloem.nl/blog/transformers') blog.


In [1]:
# IMPORTING LIBRARIES
import torch 
from torch import nn
from torch.nn import LayerNorm,Dropout,Linear,Softmax
# import activation function named softmax
import torch.nn.functional as F
from torch.nn import Embedding
import torch.nn.functional as F
from sklearn.metrics import f1_score
import torchtext
from torchtext import datasets,data
from torchtext.data import Field # Field is used to further generate mapping ids of each word using build_vocab fucntion for training data

In [2]:
# Load dataset
import pandas as pd
import numpy as np
train_data = pd.read_csv('../input/trainingtest/cleaned_train_fina.csv')['user_review'].values
labels = list(pd.read_csv('../input/trainingtest/train.csv')['user_suggestion'].values)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(train_data,labels,test_size=0.2)
# now generate different csvs for trianing and validation data
# save both train_csv and test_csv with .csv extension


In [3]:
len(x_test)

3499

In [4]:
train_csv = pd.DataFrame({'user_review':x_train,'user_suggestion':y_train})
test_csv = pd.DataFrame({'user_review':x_test,'user_suggestion':y_test})

In [11]:
# create datafield for text and label
TEXT = data.Field(sequential=True,include_lengths=True,batch_first=True,lower=True)
LABEL = data.Field(sequential=False)

train,val = data.TabularDataset.splits(format='csv',fields=[('text',TEXT),('label',LABEL)],path='../input/torchtext2/',train='train (2).csv',validation='val.csv',skip_header=True)
# now write BucketIterator for train and val dataset
TEXT.build_vocab(train,max_size=17494)
LABEL.build_vocab(train)
train_iter,val_iter = data.BucketIterator.splits(datasets=(train,val),batch_size=32,device=torch.device('cpu'),sort=False,sort_key = lambda x:len(x.user_review),sort_within_batch=False,repeat=False)


In [12]:
len(train_iter)

438

In [13]:
len(TEXT.vocab)

17496

In [14]:
import tqdm
len(val_iter)

110

In [15]:
for b in train_iter:
    print(b.label-1,type(b.text[0]))
    print(b.text[0].tolist()[31][:100])
    print(torch.LongTensor(b.text[0]))
    ls = [b.text[0].tolist()[x][:50] for x in range(32)]
    

tensor([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 1, 1, 0, 1]) <class 'torch.Tensor'>
[567, 647, 1131, 14, 11577, 3, 1416, 1618, 5, 14801, 9, 18, 5, 148, 2, 1110, 218, 4, 2617, 116, 2, 276, 5, 980, 0, 2190, 840, 1659, 12, 1097, 1924, 136, 1060, 143, 335, 2, 3650, 324, 233, 4000, 6, 5897, 2, 425, 2, 14308, 1438, 226, 1575, 43, 1342, 1300, 18, 18, 2, 2037, 792, 207, 2581, 746, 2, 84, 854, 52, 1741, 278, 1156, 2, 3169, 603, 1235, 10, 243, 2, 754, 358, 2, 149, 2, 2191, 261, 253, 1227, 398, 1382, 886, 49, 2558, 2404, 1150, 108, 396, 138, 1214, 3, 2, 2387, 2, 664, 3]
tensor([[4552,  382,   19,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1],
        ...,
        [  17,   14, 2341,  ...,    1,    1,    1],
        [   4,   64,  502,  ...,  307,  962,   30],
        [ 567,  647, 1131,  ...,    1,    1,    1]])
tensor([0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 

tensor([0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1]) <class 'torch.Tensor'>
[84, 35, 3, 2, 4, 696, 7, 2, 19, 442, 3247, 184, 775, 1064, 434, 155, 51, 0, 1150, 12, 248, 2282, 446, 432, 2, 245, 2759, 2, 28, 11, 308, 1238, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  84,   31,   48,  ...,    1,    1,    1],
        [  17,   14,  758,  ...,    1,    1,    1],
        [  17,   14, 6365,  ...,    1,    1,    1],
        ...,
        [1092,  454,  299,  ..., 1469, 3573,  128],
        [  17,   14, 9120,  ...,    1,    1,    1],
        [  84,   35,    3,  ...,    1,    1,    1]])
tensor([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 0, 0, 0, 0]) <class 'torch.Tensor'>
[162, 272, 2151, 4169, 2, 3, 271, 2, 182, 527, 1866, 4

tensor([1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 1, 1, 0, 0, 1, 1]) <class 'torch.Tensor'>
[17, 14, 107, 1159, 6, 1290, 260, 2190, 373, 2, 4, 266, 3588, 537, 4387, 2, 83, 102, 2, 924, 1280, 77, 31, 226, 1204, 198, 3, 2, 1655, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[   74,     4,     0,  ...,     1,     1,     1],
        [   45,   286,   374,  ...,     1,     1,     1],
        [   17,    14, 13979,  ...,     1,     1,     1],
        ...,
        [    4,    64,    27,  ...,     1,     1,     1],
        [   81,     5,    16,  ...,     1,     1,     1],
        [   17,    14,   107,  ...,     1,     1,     1]])
tensor([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1, 0, 0, 0]) <class 'torch.Tensor'>
[3590, 186, 1983, 

tensor([1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0]) <class 'torch.Tensor'>
[1057, 477, 1606, 0, 2, 1502, 2, 3929, 292, 1596, 2, 304, 43, 2, 92, 31, 5190, 6040, 109, 754, 2070, 164, 2, 807, 194, 2, 10, 0, 8436, 2, 2021, 1502, 1113, 126, 0, 3717, 3718, 2, 4, 73, 1349, 40, 2, 16, 3, 9, 37, 942, 119, 12, 248, 1588, 578, 424, 1325, 8452, 1811, 324, 141, 2, 12, 5, 230, 2, 930, 9384, 36, 2489, 23, 12, 5, 128, 499, 1480, 772, 0, 9475, 3065, 71, 4052, 697, 169, 98, 41, 163, 206, 2, 1863, 99, 505, 1353, 43, 2, 1481, 84, 4, 36, 2, 4412, 405]
tensor([[1281,   51,   66,  ...,    1,    1,    1],
        [4453,    2,   51,  ...,    1,    1,    1],
        [  17,   14, 5341,  ...,    1,    1,    1],
        ...,
        [ 254,  113,  179,  ...,    1,    1,    1],
        [   4,   65,    3,  ...,    1,    1,    1],
        [1057,  477, 1606,  ...,    1,    1,    1]])
tensor([0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

tensor([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 0]) <class 'torch.Tensor'>
[16, 3, 1486, 72, 2, 561, 1666, 679, 416, 846, 2, 10, 0, 155, 335, 2, 4, 34, 8, 25, 4316, 562, 1334, 36, 10268, 14166, 11397, 2, 363, 858, 5861, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[ 421,    4,  581,  ...,    1,    1,    1],
        [ 562,  171,    3,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1],
        ...,
        [ 251,   27,  348,  ...,    1,    1,    1],
        [2020, 1376,    2,  ...,    1,    1,    1],
        [  16,    3, 1486,  ...,    1,    1,    1]])
tensor([1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 0, 0, 0]) <class 'torch.Tensor'>
[16, 342, 9, 2, 49, 0, 2, 4, 41, 0, 2, 10, 0, 442,

tensor([[  16,    3,  154,  ...,    1,    1,    1],
        [  17,   14, 9130,  ...,    1,    1,    1],
        [  17,   14, 3197,  ...,    1,    1,    1],
        ...,
        [3016,  668,  280,  ...,    1,    1,    1],
        [   4,  650, 4080,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1]])
tensor([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 1]) <class 'torch.Tensor'>
[14, 269, 3, 208, 364, 19, 2722, 2, 7, 2, 35, 100, 2, 212, 543, 35, 2, 37, 189, 109, 3705, 5132, 769, 2, 7, 680, 1064, 453, 119, 12, 102, 2351, 1580, 2, 2354, 6280, 0, 0, 2, 214, 497, 4, 375, 819, 454, 249, 2, 55, 771, 819, 2, 281, 964, 3539, 1611, 7, 2, 2999, 1246, 2, 213, 110, 544, 1929, 2, 134, 9637, 5225, 2, 1648, 13735, 5225, 2, 509, 2, 651, 4627, 135, 13, 7, 2, 10, 224, 196, 5669, 732, 39, 698, 183, 2, 183, 23, 220, 103, 32, 2, 163, 28, 2, 38]
tensor([[6033,   91,    0,  ...,    1,    1,    1],
        [  74,  341,    3,  ...,

tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 1, 0]) <class 'torch.Tensor'>
[458, 22, 9, 428, 2, 561, 4, 403, 1171, 426, 3, 117, 33, 2, 621, 33, 0, 271, 3, 2, 73, 68, 1883, 126, 9767, 457, 93, 1804, 2, 1355, 354, 1145, 1266, 442, 7, 144, 140, 428, 2669, 1900, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  17,   14, 1133,  ...,    1,    1,    1],
        [  17,   14,    0,  ...,    1,    1,    1],
        [1091,    0, 2386,  ...,    1,    1,    1],
        ...,
        [  13, 6610,    2,  ...,    1,    1,    1],
        [ 553,    3,    2,  ...,    1,    1,    1],
        [ 458,   22,    9,  ...,    1,    1,    1]])
tensor([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 1]) <class 'torch.Tensor'>
[231, 55, 3, 238, 334, 20, 2, 1086, 54

tensor([1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 1]) <class 'torch.Tensor'>
[17, 14, 7217, 0, 583, 0, 99, 345, 668, 63, 3, 1489, 240, 0, 15, 2130, 520, 221, 251, 183, 2, 18, 683, 408, 13351, 574, 3785, 13453, 663, 458, 873, 210, 352, 6216, 586, 43, 0, 7811, 4, 154, 85, 4013, 104, 448, 2, 594, 742, 13, 1151, 158, 12745, 118, 37, 15120, 15453, 234, 489, 1407, 5993, 2, 254, 272, 1158, 1910, 2308, 6214, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  16,    3,  535,  ...,    1,    1,    1],
        [  41,    3,   59,  ...,    1,    1,    1],
        [  35,  695,  164,  ...,    1,    1,    1],
        ...,
        [  92, 2071,    3,  ...,    1,    1,    1],
        [   4,   64, 2675,  ...,    2,  455, 3453],
        [  17,   14, 7217,  ...,    1,    1,    1]])
tensor([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 

tensor([1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 1]) <class 'torch.Tensor'>
[519, 494, 40, 12, 602, 1678, 141, 2, 63, 8691, 2, 424, 2, 10087, 1807, 2, 13586, 6, 7167, 2663, 1042, 2, 548, 699, 851, 1226, 555, 7, 513, 192, 52, 118, 69, 2, 4908, 2, 4, 85, 278, 343, 9, 3, 1221, 5, 49, 25, 3605, 6688, 2, 1291, 2145, 2, 7819, 1832, 240, 3423, 1917, 5374, 6843, 200, 3090, 2, 7, 863, 10019, 2, 989, 296, 3, 2, 409, 0, 0, 108, 679, 555, 2, 7, 11, 404, 14285, 126, 15063, 9710, 13, 0, 2, 111, 359, 130, 920, 18, 2705, 74, 136, 27, 21, 2424, 2705, 2]
tensor([[  17,   14, 4973,  ...,    1,    1,    1],
        [ 798,    2,    3,  ...,    1,    1,    1],
        [2578,    5, 4005,  ...,    1,    1,    1],
        ...,
        [  17,   14, 3376,  ...,    1,    1,    1],
        [  14, 5551, 1051,  ...,    1,    1,    1],
        [ 519,  494,   40,  ...,    0,    0,    0]])
tensor([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 

tensor([0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
        1, 1, 0, 0, 1, 0, 1, 1]) <class 'torch.Tensor'>
[125, 1323, 40, 154, 20, 3, 12, 1511, 143, 2, 45, 4, 1019, 27, 794, 57, 153, 365, 238, 885, 31, 395, 99, 1019, 2, 286, 36, 3, 10, 0, 204, 788, 2, 177, 22, 9, 2, 25, 251, 9, 2, 102, 25, 395, 2, 83, 435, 192, 2, 484, 583, 2472, 125, 2, 2568, 75, 15, 2, 364, 135, 2, 46, 332, 47, 19, 1257, 3593, 135, 2, 2762, 165, 2, 152, 3, 2, 1007, 67, 93, 2, 3934, 1286, 815, 130, 1353, 972, 2, 2018, 2104, 685, 3, 32, 11, 43, 56, 1259, 683, 646, 4199, 1972, 49]
tensor([[ 125, 1323,   40,  ...,    1,    1,    1],
        [  17,   14, 5552,  ...,    1,    1,    1],
        [  63,  712, 5232,  ...,    2,  561,    2],
        ...,
        [  17,   14,  223,  ...,    1,    1,    1],
        [ 240,  290, 2042,  ...,    1,    1,    1],
        [ 125, 1323,   40,  ...,    1,    1,    1]])
tensor([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 

tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 1]) <class 'torch.Tensor'>
[16, 3, 910, 1244, 616, 397, 2160, 60, 34, 8, 2160, 60, 616, 134, 60, 2, 616, 374, 397, 91, 44, 91, 1094, 733, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[ 39, 599, 141,  ...,   1,   1,   1],
        [  2, 729,   5,  ...,   1,   1,   1],
        [467,  74,   2,  ...,   1,   1,   1],
        ...,
        [  4,   3, 898,  ...,   1,   1,   1],
        [ 17,  14,   0,  ...,   1,   1,   1],
        [ 16,   3, 910,  ...,   1,   1,   1]])
tensor([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 0, 1, 0]) <class 'torch.Tensor'>
[17, 14, 3042, 220, 3, 50, 6677, 94, 84, 773, 3095, 613, 5266, 272, 15, 82, 725, 272, 9814, 8488, 6

tensor([0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1]) <class 'torch.Tensor'>
[55, 72, 2, 82, 25, 113, 3, 58, 538, 788, 2, 730, 3788, 1162, 92, 244, 2, 29, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  17,   14, 5787,  ...,    1,    1,    1],
        [ 188,   63,  149,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1],
        ...,
        [1664,  389,   19,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1],
        [  55,   72,    2,  ...,    1,    1,    1]])
tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
        0, 1, 0, 1, 1, 1, 1, 0]) <class 'torch.Tensor'>
[17, 14, 1133, 19, 3, 9, 122, 209, 676, 916, 1538, 314, 13, 270, 37, 2, 26, 32

tensor([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0]) <class 'torch.Tensor'>
[17, 14, 269, 3, 44, 1144, 370, 10, 540, 1427, 35, 85, 384, 48, 560, 979, 14, 2, 32, 59, 249, 725, 2, 638, 1936, 42, 3542, 63, 673, 2, 10, 0, 803, 2, 968, 1431, 3307, 100, 10, 2745, 50, 2207, 815, 152, 20, 10, 198, 5298, 43, 137, 271, 3, 4, 53, 3385, 4565, 1427, 2, 0, 4, 34, 8, 250, 7502, 225, 2775, 8943, 49, 21, 88, 2, 10, 11, 19, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[   29,     8,  1061,  ...,     1,     1,     1],
        [  567,   647, 11041,  ...,     1,     1,     1],
        [    4,   169,    41,  ...,     1,     1,     1],
        ...,
        [  154,    96,     3,  ...,     1,     1,     1],
        [    6,   141,     0,  ...,     1,     1,     1],
        [   17,    14,   269,  ...,     1,     1,     1]])
tensor([1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        1,

tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 1, 1]) <class 'torch.Tensor'>
[839, 3, 4, 359, 23, 94, 12, 76, 724, 319, 327, 2, 393, 9, 21, 211, 37, 294, 641, 85, 127, 0, 6, 0, 342, 209, 46, 78, 677, 117, 33, 2, 0, 1378, 26, 67, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[ 669,    4,   96,  ...,    1,    1,    1],
        [ 301,   18,  948,  ...,    1,    1,    1],
        [ 231,   55,   37,  ...,    1,    1,    1],
        ...,
        [  37,  113,  549,  ...,    1,    1,    1],
        [  17,   14, 2527,  ...,    1,    1,    1],
        [ 839,    3,    4,  ...,    1,    1,    1]])
tensor([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0]) <class 'torch.Tensor'>
[17, 14, 1805, 719, 3, 2, 35, 1698, 2, 632, 1272, 5933, 12

tensor([[  17,   14,    0,  ...,    1,    1,    1],
        [  19,   18, 2348,  ...,    1,    1,    1],
        [1197,   71, 1255,  ...,    1,    1,    1],
        ...,
        [  54,   69,   41,  ...,    1,    1,    1],
        [ 154,   19,   99,  ...,    1,    1,    1],
        [   4,   26,  590,  ...,    1,    1,    1]])
tensor([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 1, 0, 0]) <class 'torch.Tensor'>
[2893, 20, 3, 145, 989, 2, 38, 722, 13, 5677, 2824, 157, 1169, 855, 108, 213, 157, 2, 760, 403, 612, 1339, 2836, 24, 936, 112, 2, 667, 1263, 4767, 3, 2, 2706, 2, 8268, 153, 2, 2893, 2, 1152, 2, 26, 19, 2283, 674, 416, 2, 109, 35, 18, 3144, 27, 1152, 786, 4695, 883, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  92, 1135, 1995,  ...,    1,    1,    1],
        [1148,  183,  742,  ...,    1,    1,    1],
        [7096, 5592, 4468,  ...,    

tensor([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0]) <class 'torch.Tensor'>
[17, 14, 2527, 244, 20, 185, 3, 743, 2, 4, 70, 38, 12, 7, 2, 50, 870, 1537, 442, 2, 44, 1008, 186, 73, 68, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[ 214,  562,  812,  ...,    1,    1,    1],
        [  10,  923,  197,  ...,    1,    1,    1],
        [1474, 1664,   99,  ...,    1,    1,    1],
        ...,
        [1468,  870,  846,  ...,    1,    1,    1],
        [  17,   14, 6038,  ...,    1,    1,    1],
        [  17,   14, 2527,  ...,    1,    1,    1]])
tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 1, 0, 1, 1, 1, 1, 1]) <class 'torch.Tensor'>
[17, 14, 269, 3, 830, 2, 1247, 2, 104, 618, 2, 212, 1004, 8, 2, 470, 1

tensor([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 1]) <class 'torch.Tensor'>
[2384, 1305, 2, 827, 302, 386, 3, 2, 84, 2, 2515, 2, 1556, 2, 443, 6, 1239, 164, 695, 6790, 2, 827, 2, 3, 561, 130, 33, 5, 311, 1687, 2, 90, 4297, 78, 60, 2, 39, 37, 82, 4, 85, 28, 2, 502, 163, 74, 2, 52, 101, 262, 2, 62, 2, 62, 3311, 2, 2576, 1645, 2, 410, 506, 47, 107, 682, 3311, 93, 2, 306, 935, 89, 637, 55, 408, 2, 4, 53, 1103, 5119, 112, 132, 13, 2490, 201, 262, 2, 162, 8153, 326, 413, 302, 2, 1125, 2945, 16, 2, 4, 97, 741, 355, 262]
tensor([[  15,   82,    4,  ...,    1,    1,    1],
        [ 170,   22,    3,  ...,    1,    1,    1],
        [  10, 8557,   52,  ...,    1,    1,    1],
        ...,
        [  17,   14, 2993,  ...,   22,    2,    7],
        [ 424,  906,   19,  ...,    1,    1,    1],
        [2384, 1305,    2,  ...,    1,    1,    1]])
tensor([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0

tensor([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 0]) <class 'torch.Tensor'>
[17, 14, 5788, 1192, 3, 51, 6, 54, 6, 66, 2, 1255, 737, 1457, 4, 64, 111, 325, 469, 2, 1208, 2498, 2690, 2, 778, 571, 2, 104, 2, 11666, 2, 899, 3484, 189, 2850, 827, 2198, 63, 471, 4265, 697, 2, 983, 37, 276, 781, 105, 3617, 2, 32, 11, 596, 216, 23, 400, 65, 3, 208, 1467, 516, 2, 133, 107, 515, 1243, 44, 1708, 2, 378, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  17,   14,    0,  ...,    1,    1,    1],
        [  17,   14, 6754,  ...,    1,    1,    1],
        [  17,   14,  758,  ...,    1,    1,    1],
        ...,
        [ 656,    2,   74,  ...,    1,    1,    1],
        [  84,   19,    3,  ...,    1,    1,    1],
        [  17,   14, 5788,  ...,    1,    1,    1]])
tensor([0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
        0, 1, 0, 1, 1, 1, 1, 0]) <class 'torc

tensor([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 1]) <class 'torch.Tensor'>
[29, 8, 13, 399, 3, 59, 20, 416, 21, 679, 0, 113, 197, 0, 22, 9, 4015, 128, 2605, 339, 985, 2, 2558, 542, 37, 47, 117, 419, 2, 4, 97, 73, 3015, 2, 32, 1602, 403, 371, 6, 795, 2552, 580, 1437, 71, 436, 4249, 0, 1761, 7833, 1014, 5, 1014, 91, 3179, 1434, 597, 778, 724, 78, 328, 116, 15, 524, 2764, 2178, 2, 34, 5906, 1761, 2, 255, 143, 181, 56, 9902, 500, 97, 69, 232, 688, 669, 1190, 847, 61, 5, 12102, 2495, 0, 90, 76, 61, 14938, 670, 5394, 299, 9, 2, 368, 512, 2]
tensor([[ 1149,  1251,     2,  ...,     1,     1,     1],
        [   98,    99,     4,  ...,     1,     1,     1],
        [   35,  9412,  5190,  ...,     1,     1,     1],
        ...,
        [   10,     3,    19,  ...,     1,     1,     1],
        [   17,    14, 10179,  ...,     1,     1,     1],
        [   29,     8,    13,  ...,   358,   184,   388]])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 1

tensor([[  17,   14, 4218,  ...,    1,    1,    1],
        [  84, 1243, 1599,  ...,    1,    1,    1],
        [ 494,   40,    2,  ...,    1,    1,    1],
        ...,
        [ 567,  647, 1131,  ...,    1,    1,    1],
        [ 804,    3, 1545,  ...,    1,    1,    1],
        [  17,   14, 3998,  ...,    1,    1,    1]])
tensor([1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 1, 0]) <class 'torch.Tensor'>
[4, 2003, 3530, 52, 41, 101, 2, 469, 556, 101, 1021, 226, 2, 49, 18, 27, 2, 25, 115, 437, 513, 792, 755, 2, 44, 145, 892, 1315, 31, 2, 74, 62, 482, 2, 31, 312, 155, 2, 144, 112, 32, 11, 161, 2635, 791, 280, 2112, 2, 155, 6, 796, 268, 42, 2363, 2, 2454, 2754, 2, 3098, 52, 2, 738, 9, 134, 52, 2, 313, 1399, 851, 1913, 271, 2279, 2, 152, 2, 294, 1482, 2598, 2, 10, 3, 232, 127, 674, 343, 43, 2, 485, 1046, 4576, 580, 203, 75, 82, 13, 251, 2, 116, 1129, 2333]
tensor([[  83,  374,  602,  ...,    1,    1,    1],
        [  17,   14,  269,  .

tensor([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 1]) <class 'torch.Tensor'>
[798, 3, 26, 4161, 7057, 2, 4, 154, 96, 2584, 238, 12, 540, 826, 125, 2353, 5516, 678, 33, 118, 135, 554, 178, 268, 2524, 2, 2220, 81, 3643, 1331, 95, 2372, 75, 591, 1634, 172, 604, 524, 332, 1762, 2, 40, 351, 1382, 2, 20, 299, 209, 2950, 62, 461, 513, 309, 395, 105, 3790, 166, 1759, 1466, 769, 9173, 1753, 246, 0, 455, 1828, 4, 53, 4144, 0, 70, 716, 31, 531, 77, 8474, 331, 2, 227, 1470, 111, 0, 742, 2, 207, 497, 15, 3383, 117, 20, 2, 234, 25, 71, 6, 13279, 7474, 5, 2017, 1588]
tensor([[  17,   14, 4355,  ...,    1,    1,    1],
        [1062, 1425,   91,  ...,    1,    1,    1],
        [  39,  185,   19,  ...,    1,    1,    1],
        ...,
        [  17,   14, 1914,  ...,    1,    1,    1],
        [   3,  271,    2,  ...,    2,    0,    0],
        [ 798,    3,   26,  ...,    1,    1,    1]])
tensor([0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 

tensor([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        1, 1, 0, 0, 0, 1, 0, 1]) <class 'torch.Tensor'>
[7, 310, 59, 139, 116, 432, 2, 926, 354, 5, 1745, 392, 84, 2, 1782, 775, 1191, 93, 90, 39, 127, 1566, 13, 425, 23, 47, 3, 422, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  16,   71,    3,  ...,    1,    1,    1],
        [ 160,   59,   12,  ...,    1,    1,    1],
        [ 712, 1271, 1354,  ...,    1,    1,    1],
        ...,
        [  16,    3,  731,  ...,    1,    1,    1],
        [ 125, 1323,   40,  ...,    1,    1,    1],
        [   7,  310,   59,  ...,    1,    1,    1]])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0]) <class 'torch.Tensor'>
[16, 3, 35, 378, 2, 481, 38, 1283, 5451, 1515, 452, 2, 26, 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 1, 1, 0]) <class 'torch.Tensor'>
[4, 531, 2, 1487, 2, 28, 23, 267, 607, 743, 3, 1853, 5379, 263, 2, 7, 47, 31, 3535, 2, 50, 2, 132, 24, 2, 150, 178, 13, 21, 2, 16, 21, 118, 190, 736, 20, 304, 1731, 75, 798, 2, 468, 194, 2, 73, 58, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[   35,     3,  1538,  ...,     1,     1,     1],
        [   16,     3,    20,  ...,     1,     1,     1],
        [   21,  1787,  1526,  ...,     1,     1,     1],
        ...,
        [   40, 11650, 14130,  ...,     1,     1,     1],
        [  751,    26,  1480,  ...,     1,     1,     1],
        [    4,   531,     2,  ...,     1,     1,     1]])
tensor([1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 1, 0, 0]) <class 'torch.Tensor'>
[17, 1

tensor([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0]) <class 'torch.Tensor'>
[17, 14, 3198, 20, 3, 2, 9, 141, 173, 2, 3053, 2, 2535, 2, 3, 127, 151, 13, 154, 416, 167, 0, 163, 2, 400, 1836, 41, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  84,  912,   28,  ...,    1,    1,    1],
        [   4,   64,   41,  ...,    1,    1,    1],
        [ 892,  285, 1315,  ...,    1,    1,    1],
        ...,
        [  10,    3, 1253,  ...,    1,    1,    1],
        [  45,    3, 4369,  ...,    1,    1,    1],
        [  17,   14, 3198,  ...,    1,    1,    1]])
tensor([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0]) <class 'torch.Tensor'>
[2541, 4, 25, 82, 9, 3, 2, 234, 2497, 139, 252, 138, 48, 3, 707, 4

tensor([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
        1, 1, 1, 0, 1, 1, 1, 0]) <class 'torch.Tensor'>
[4, 12, 3, 2, 340, 674, 82, 1712, 2, 23, 144, 276, 570, 471, 4555, 70, 1418, 488, 169, 2, 10, 1661, 45, 4042, 105, 59, 2319, 2418, 1044, 29, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[7249,    5,   44,  ...,    1,    1,    1],
        [ 359,   23,   19,  ...,    1,    1,    1],
        [   4,  642, 1324,  ...,    1,    1,    1],
        ...,
        [ 284,  679,  149,  ...,    1,    1,    1],
        [  17,   14,  758,  ...,    1,    1,    1],
        [   4,   12,    3,  ...,    1,    1,    1]])
tensor([0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 1, 0]) <class 'torch.Tensor'>
[990, 1499, 220, 103, 2, 6447, 260, 947, 2, 482, 2,

tensor([0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 1, 1, 1, 0, 1]) <class 'torch.Tensor'>
[74, 5, 4, 64, 41, 3, 7625, 255, 52, 2, 209, 4, 2075, 2, 1292, 495, 107, 55, 72, 2, 4, 53, 1239, 3816, 2, 598, 12, 83, 123, 406, 654, 1125, 2, 361, 2462, 3816, 2, 969, 8016, 427, 2, 50, 21, 1387, 89, 687, 5492, 2041, 2, 186, 18, 2, 1631, 9903, 352, 578, 586, 2310, 2088, 0, 2, 180, 34, 8, 1006, 0, 1281, 24, 16, 2, 855, 5278, 249, 23, 144, 60, 700, 859, 743, 148, 2, 1344, 375, 790, 11761, 7717, 74, 6931, 2506, 2184, 2, 31, 119, 73, 1332, 509, 86, 52, 150, 178]
tensor([[   4,  590,   31,  ...,    1,    1,    1],
        [1165, 8909,   51,  ...,    1,    1,    1],
        [  16,    3,  225,  ...,    1,    1,    1],
        ...,
        [ 284,   30,   52,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1],
        [  74,    5,    4,  ...,  407,   59,  378]])
tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0

tensor([1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 1, 1, 0, 1, 0, 0]) <class 'torch.Tensor'>
[7, 71, 100, 98, 2, 16, 3, 150, 178, 119, 22, 2, 196, 135, 2, 99, 1669, 315, 780, 30, 759, 5, 46, 2, 748, 819, 602, 3168, 2, 980, 189, 3168, 2, 115, 4, 878, 243, 21, 2, 232, 105, 333, 5, 163, 281, 28, 2, 144, 112, 2, 994, 56, 2, 104, 366, 2, 236, 366, 548, 662, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  84, 6858,  262,  ...,    1,    1,    1],
        [ 214,  107,  494,  ...,    1,    1,    1],
        [ 513,   30,   52,  ...,    1,    1,    1],
        ...,
        [2801,    2,    4,  ...,    1,    1,    1],
        [  17,   14, 3676,  ...,    1,    1,    1],
        [   7,   71,  100,  ...,    1,    1,    1]])
tensor([1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 0, 0]) <class 'torch.Tensor'>
[16, 3, 170, 2, 4, 5

tensor([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 0]) <class 'torch.Tensor'>
[4, 783, 3, 1332, 194, 2, 1480, 107, 2, 590, 5092, 2, 148, 2, 145, 132, 4958, 4450, 7, 2, 39, 21, 18, 78, 2, 20, 58, 2, 4, 23, 51, 117, 33, 50, 1692, 2, 13, 31, 80, 2, 121, 537, 2, 45, 220, 2, 15, 1080, 865, 195, 165, 2, 92, 337, 2, 7, 11, 127, 2, 3043, 6, 2921, 5, 56, 2, 7300, 2, 70, 2463, 10105, 2, 7300, 73, 8703, 1191, 1189, 3493, 2, 8, 67, 2, 120, 16404, 2, 377, 662, 601, 77, 622, 2, 80, 1191, 2, 360, 2, 241, 2, 975, 17054, 2]
tensor([[  84,  345,    3,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1],
        [3149, 4035,  781,  ...,    1,    1,    1],
        ...,
        [  15,  561, 5254,  ...,    1,    1,    1],
        [  12,  812,   78,  ...,    1,    1,    1],
        [   4,  783,    3,  ...,    1,    1,    1]])
tensor([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 

tensor([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 1, 0, 0, 0]) <class 'torch.Tensor'>
[4, 26, 859, 3, 2, 20, 1678, 744, 11631, 44, 598, 4468, 117, 33, 1512, 37, 145, 3, 526, 152, 0, 187, 2, 39, 113, 4329, 761, 78, 134, 681, 2065, 526, 39, 1341, 120, 19, 2, 7, 22, 9, 72, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  17,   14,  223,  ...,    1,    1,    1],
        [ 219,   29,    8,  ...,    1,    1,    1],
        [  17,   14, 4638,  ...,   94,   36, 1045],
        ...,
        [1138, 3383,  798,  ...,    1,    1,    1],
        [  17,   14,  269,  ...,    1,    1,    1],
        [   4,   26,  859,  ...,    1,    1,    1]])
tensor([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 1, 1]) <class 'torch.Tensor'>
[20, 185, 3, 28, 11, 69, 7, 2, 164, 238,

tensor([[  74,  337,    2,  ...,    1,    1,    1],
        [  17,   14, 8373,  ...,    1,    1,    1],
        [  20,   24,  122,  ...,    1,    1,    1],
        ...,
        [  16,    3, 1115,  ...,  847,  369,   11],
        [   4,   53,   90,  ...,    1,    1,    1],
        [  17,   14,  269,  ...,    1,    1,    1]])
tensor([1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 1]) <class 'torch.Tensor'>
[465, 731, 67, 2, 25, 739, 602, 183, 1678, 2, 4, 2973, 85, 1334, 2, 1730, 610, 99, 243, 298, 2, 4, 53, 200, 2046, 457, 2, 27, 521, 2, 24, 640, 3, 154, 167, 2, 317, 128, 290, 97, 93, 2, 457, 8, 2, 18, 105, 7987, 1604, 15, 2, 1919, 55, 3926, 566, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[    4,    26,   187,  ...,     1,     1,     1],
        [   17,    14,  6760,  ...,     1,     1,     1],
        [   27,  2619,   122,  ...,     1,

tensor([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 1]) <class 'torch.Tensor'>
[1094, 279, 3391, 25, 1054, 1544, 2, 4, 53, 329, 2046, 0, 230, 159, 6394, 86, 377, 572, 1563, 2, 1492, 3331, 2803, 5255, 456, 40, 6, 456, 0, 496, 2, 111, 381, 24, 1893, 2025, 2, 3, 434, 2111, 918, 627, 137, 7865, 2, 1671, 497, 29, 8, 65, 3, 2, 196, 242, 1356, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  21,   88,    4,  ...,    1,    1,    1],
        [  16,   20,  246,  ...,    1,    1,    1],
        [  45,    3,  744,  ...,    1,    1,    1],
        ...,
        [  17,   14, 7218,  ...,    1,    1,    1],
        [  84,   92,  244,  ...,    1,    1,    1],
        [1094,  279, 3391,  ...,    1,    1,    1]])
tensor([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 1]) <class 'torch.Tensor'>
[17, 14

tensor([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 1, 1]) <class 'torch.Tensor'>
[17, 14, 223, 321, 5, 474, 9, 22, 24, 2, 180, 3, 2, 39, 45, 5, 3, 252, 12, 1616, 298, 207, 2, 901, 2402, 5810, 6530, 1796, 2, 5700, 2793, 2, 212, 586, 779, 1426, 1218, 195, 430, 2107, 2, 294, 592, 338, 1194, 2332, 1029, 819, 277, 2, 4, 574, 77, 69, 260, 6, 253, 217, 31, 48, 2, 1846, 19, 82, 48, 807, 2, 129, 445, 6673, 0, 2281, 121, 1502, 58, 224, 27, 34, 8, 672, 21, 2, 28, 11, 870, 2, 1037, 2, 34, 78, 505, 763, 709, 2, 1157, 7, 97, 48, 1, 1]
tensor([[  20,    3, 2955,  ...,    1,    1,    1],
        [  35,    3,    2,  ...,    1,    1,    1],
        [  17,   14, 6761,  ...,    1,    1,    1],
        ...,
        [  17,   14, 9121,  ...,    1,    1,    1],
        [   4,   64,  494,  ...,    1,    1,    1],
        [  17,   14,  223,  ...,    1,    1,    1]])
tensor([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        0, 1

tensor([[  17,   14,  223,  ...,    1,    1,    1],
        [  17,   14,  107,  ...,    1,    1,    1],
        [  10,    3,   71,  ...,    1,    1,    1],
        ...,
        [ 656,    4, 2945,  ...,    1,    1,    1],
        [  29,    8,   13,  ...,    1,    1,    1],
        [ 567,  647, 1131,  ...,    1,    1,    1]])
tensor([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 1, 1, 1, 0]) <class 'torch.Tensor'>
[17, 14, 0, 91, 80, 117, 2, 45, 220, 2, 237, 950, 3722, 1795, 408, 58, 1582, 3, 2, 1063, 192, 917, 2, 56, 0, 34, 861, 243, 596, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[  17,   14,  223,  ...,    1,    1,    1],
        [ 744, 2492,  253,  ...,    1,    1,    1],
        [  17,   14, 1133,  ...,    1,    1,    1],
        ...,
        [ 284,   27,  751,  

tensor([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 0]) <class 'torch.Tensor'>
[41, 3, 98, 99, 1439, 345, 251, 2, 20, 171, 3, 2, 8, 216, 36, 2734, 3459, 12, 2268, 2, 4, 23, 905, 200, 179, 2, 7, 11, 51, 66, 19, 203, 146, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[   7,   11,   35,  ...,    1,    1,    1],
        [  35,    3,    2,  ...,    1,    1,    1],
        [  16,  107,  706,  ...,    1,    1,    1],
        ...,
        [   7,   11,  957,  ...,    1,    1,    1],
        [  17,   14, 6762,  ...,    1,    1,    1],
        [  41,    3,   98,  ...,    1,    1,    1]])
tensor([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 1, 1, 0]) <class 'torch.Tensor'>
[4, 64, 3518, 3, 197, 862, 555, 4, 26, 1043, 175, 2, 41, 190

IndexError: list index out of range

In [16]:
len(ls)

32

In [17]:
import pandas as pd
import numpy as np
train_data = pd.read_csv('../input/trainingtest/cleaned_train_fina.csv')['user_review'].values
labels = list(pd.read_csv('../input/trainingtest/train.csv')['user_suggestion'].values)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(train_data,labels,test_size=0.2)
train_data = np.array(train_data)
train_data = list(train_data)
labels = list(y_train)

test_data = train_data
print(test_data[0])
final_data = []
import re
for data in test_data:
    new = re.sub('[0-9]','',str(data))
    final_data.append(new)
print(final_data[0])
from tensorflow.keras.preprocessing import text,sequence

tokenize = text.Tokenizer()

tokenize.fit_on_texts(texts = (final_data))
index_data = tokenize.texts_to_sequences(final_data)

word_index = tokenize.word_index

i m scared hearing creepy voices  so i will pause moment write review i wait heart beat return atleast somewhat calmer times  this game adorable like happy tree friends graphics sceme childhood  but bubble  clean    hello 1990 s what charactes  that isnot trying kill me  likable bit odd  noob things though  as oh look class room full ghosts dead children  let us shine flashlight stand staring them  or  hmm music  turn around see what is chasing me never afraid finding locked door 
i m scared hearing creepy voices  so i will pause moment write review i wait heart beat return atleast somewhat calmer times  this game adorable like happy tree friends graphics sceme childhood  but bubble  clean    hello  s what charactes  that isnot trying kill me  likable bit odd  noob things though  as oh look class room full ghosts dead children  let us shine flashlight stand staring them  or  hmm music  turn around see what is chasing me never afraid finding locked door 


In [18]:
# Self Attention Architecture
class selfattention(nn.Module):
    
    def __init__(self,k,heads=9):
        super().__init__()
        self.k , self.heads = k,heads
        # initialize dimensions for keys,values and queries as we are building multi-head attention layers for modern transformer
        self.tokeys = nn.Linear(k,k*heads,bias=False)
        self.toqueries = nn.Linear(k,k*heads,bias=False)
        self.tovalues = nn.Linear(k,k*heads,bias=False)
        
        self.unified = nn.Linear(k*heads,k,bias=False)
        
    def forward(self,x):  # pass values into __init__ function
        b,t,k = x.size()  # where b is number of batches, t is size of input sequence length and k is number of dimensions
        # now determine keys,values,queries and heads
        h = self.heads
        
        keys = self.tokeys(x).view(b,t,h,k) # initially we don't have head next to each other
        queries = self.toqueries(x).view(b,t,h,k)
        values = self.tovalues(x).view(b,t,h,k)
    
        # now we want head next to batch, its highly computational expensive but we have to do it, so transform keys,values and queries
        keys = keys.transpose(1,2).contiguous().view(b*h,t,k)
        queries = queries.transpose(1,2).contiguous().view(b*h,t,k)
        values = values.transpose(1,2).contiguous().view(b*h,t,k)
        # now calculate dot product using bmm function in pytorch
        dot = torch.bmm(queries,keys.transpose(1,2))
        
        dot = F.softmax(dot,dim=2)
        out = torch.bmm(dot,values).view(b,h,t,k)
        
        # now finally we want unified output in k dimensions as we have initially, so to do this again transspose out
        out = out.transpose(1,2).contiguous().view(b,t,h*k)
        out = self.unified(out)
        return out  

In [19]:
# now build architecture for transformer block
class transformer(nn.Module):
    
    def __init__(self,k,heads=9):
        super().__init__()
        self.attention = selfattention(k) # pass class named selfattention
        # now add normalization layer to normalize outputs of attention layer
        self.norm1 = nn.LayerNorm(k)
        self.norm2 = nn.LayerNorm(k)
        # now make a fully connected multi layer perceptron
        self.ff = nn.Sequential(nn.Linear(k,4*k),nn.ReLU(),nn.Linear(4*k,k)) # fully connected layer for hidden states
        self.drop = nn.Dropout(0.5)
    
    def forward(self,x):
        attention = self.attention(x)
        x = self.norm1(attention+x)
        x = self.drop(x) # dropout layer after normalization(drop some neurons to prevent from overfitting)
        perceptron = self.ff(x)
        x = self.norm2(perceptron + x)
        x = self.drop(x)
        return x

In [34]:
# now add classification and add embedding layer initially to it.
# REMEMBER INPUT SHOULD BE INDEXES OF WORDS 
class classify(nn.Module):
    
    def __init__(self,k,seq_length,num_tokens,depth,num_classes,max_pool=True,heads=9):
        super().__init__()
        # initialize tokens
        self.num_tokens = num_tokens
        self.maxpool = max_pool
        # it needs input in word indexes using tokenizer
        self.tokenemb = Embedding(embedding_dim=k,num_embeddings=num_tokens)
        # position embedding
        self.posemb = Embedding(embedding_dim=k, num_embeddings=seq_length)
        tfblocks = []
        for i in range(depth):
            tfblocks.append(transformer(k))
        # now add sequential layer of tfblocks
        self.transform = nn.Sequential(*tfblocks)
        # add linear layer to convert into desired number of class i.e. 2 for binary class
        self.prob = nn.Linear(k,num_classes)
        self.drop = nn.Dropout(0.5)
        
    def forward(self,x,y):
        tokens = self.tokenemb(x)
        b,t,k = tokens.size()
        for batch in range(b):
            for pos in range(t):
                for i in range(k):
                    if i%2==0:
                        tokens[batch][pos][i]+=np.sin(pos/(1000**(2*i/k)))
                    else:
                        tokens[batch][pos][i]+=np.cos(pos/(1000**(((2*i)+1)/k)))
        #positions = self.posemb(torch.arange(t, device=torch.device('cuda')))[None, :, :].expand(b, t, k)
        
        x = tokens # adding tokens and positions to get proper embeddings of each indexes of words
        x = self.drop(x)
        x = self.transform(x)
        x = x.max(dim=1)[0] if self.maxpool else x.mean(dim=1)
        x = self.prob(x)
        x = F.softmax(x,dim=1)
        loss = torch.nn.CrossEntropyLoss()
        loss = loss(x,y)
        return loss,x        

In [22]:
device=torch.device('cpu')

In [35]:
# initializing classify model for binary classification
classifier = classify(128,100,17496,12,2)
classifier.to(device)

classify(
  (tokenemb): Embedding(17496, 128)
  (posemb): Embedding(100, 128)
  (transform): Sequential(
    (0): transformer(
      (attention): selfattention(
        (tokeys): Linear(in_features=128, out_features=1152, bias=False)
        (toqueries): Linear(in_features=128, out_features=1152, bias=False)
        (tovalues): Linear(in_features=128, out_features=1152, bias=False)
        (unified): Linear(in_features=1152, out_features=128, bias=False)
      )
      (norm1): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=128, out_features=512, bias=True)
        (1): ReLU()
        (2): Linear(in_features=512, out_features=128, bias=True)
      )
      (drop): Dropout(p=0.5, inplace=False)
    )
    (1): transformer(
      (attention): selfattention(
        (tokeys): Linear(in_features=128, out_features=1152, bias=False)
        (toqueries): Linear(in_f

In [36]:
#pad_sequences_train,pad_sequences_test = train_test_split(pad_sequences,test_size=0.2)

In [25]:
#from torch.utils.data import DataLoader,SequentialSampler,TensorDataset,RandomSampler,DistributedSampler,BatchSampler

In [26]:
#dataset = torch.utils.data.TensorDataset(torch.LongTensor(pad_sequences_train), torch.LongTensor(labels))

In [27]:
#batch_data = DataLoader(batch_size=128,dataset = dataset,sampler = SequentialSampler(dataset))

In [28]:
'''y_test = np.array(y_test)
y_test = list(y_test)

test_dataset = TensorDataset(torch.LongTensor(pad_sequences_test),torch.LongTensor(y_test))
test_loader = DataLoader(test_dataset,batch_size=128,sampler = RandomSampler(test_dataset))'''

'y_test = np.array(y_test)\ny_test = list(y_test)\n\ntest_dataset = TensorDataset(torch.LongTensor(pad_sequences_test),torch.LongTensor(y_test))\ntest_loader = DataLoader(test_dataset,batch_size=128,sampler = RandomSampler(test_dataset))'

In [29]:
# declare optimizer 
from torch.autograd import no_grad,Variable
from torch.optim import Optimizer
from torch.optim import Adam,SGD,AdamW,lr_scheduler
optimizer = Adam(classifier.parameters(),lr=0.03,amsgrad=True)

In [30]:
''''x_test = np.array(x_test)
x_test = list(x_test)
y_test = np.array(y_test)
y_test = list(y_test)
test_data = x_test
final_data_test = []
# generating padded sequences for test data
import re
for data in test_data:
    new = re.sub('[0-9]','',str(data))
    final_data_test.append(new)
print(final_data_test[0])
from tensorflow.keras.preprocessing import text,sequence

tokenize = text.Tokenizer()

tokenize.fit_on_texts(texts = (final_data_test))
index_data_test = tokenize.texts_to_sequences(final_data_test)

word_index_test = tokenize.word_index
print(len(word_index_test))

#pad_sequences_test = sequence.pad_sequences(index_data_test,maxlen=50)

for test in test_loader:
    print(test)
    break'''

"'x_test = np.array(x_test)\nx_test = list(x_test)\ny_test = np.array(y_test)\ny_test = list(y_test)\ntest_data = x_test\nfinal_data_test = []\n# generating padded sequences for test data\nimport re\nfor data in test_data:\n    new = re.sub('[0-9]','',str(data))\n    final_data_test.append(new)\nprint(final_data_test[0])\nfrom tensorflow.keras.preprocessing import text,sequence\n\ntokenize = text.Tokenizer()\n\ntokenize.fit_on_texts(texts = (final_data_test))\nindex_data_test = tokenize.texts_to_sequences(final_data_test)\n\nword_index_test = tokenize.word_index\nprint(len(word_index_test))\n\n#pad_sequences_test = sequence.pad_sequences(index_data_test,maxlen=50)\n\nfor test in test_loader:\n    print(test)\n    break"

In [31]:
# set scheduler for learning rate, for that calculate total steps
from transformers import get_linear_schedule_with_warmup
from torch.utils.data import RandomSampler
epochs = 100 # researchers suggest to take epochs should be in range of 4-7 for fine tuning pretrained model as we have concern 
# just for last layer which is untrained classification layer.
total_steps = len(train_iter) * epochs
# scheduler take care of linear schedule of learning rate 
scheduler = get_linear_schedule_with_warmup(optimizer,num_warmup_steps=0,num_training_steps=total_steps)

In [32]:
device = torch.device('cpu')

In [ ]:
# Training 
epochs = 100
final_loss = []
output = []
testing_accuracy = []
final_test_loss=[]
for epoc in range(epochs):
    print('epoch-',epoc)
    total_loss = 0
    classifier.train()
    for batch in train_iter:
        optimizer.zero_grad()
        # now check length of input sequence whether it is greater than 512 or not
        if batch.text[0].size(1)>50:
            batch_train = batch.text[0].tolist()
            batch_train = [batch_train[x][:50] for x in range(len(batch_train))]
            
        else:
            batch_train=batch.text[0].tolist()
        loss,outputs = classifier.forward(torch.LongTensor(batch_train).to(device),(batch.label-1).to(device)) # here -2 is because of padding tokens

        loss.backward()
        total_loss+=loss.item()
        torch.nn.utils.clip_grad_norm_(classifier.parameters(),1.0)
        optimizer.step()
        scheduler.step()
    avg_loss = total_loss/len(train_iter)
    print('train_loss',avg_loss)
    final_loss.append(avg_loss) # testing outputs
    # Validating
    classifier.eval()
    test_accuracy = 0
    test_loss=0
    for batch_t in val_iter:
        with torch.no_grad():       
            if batch_t.text[0].size(1)>50:
                batch_t_test = batch_t.text[0].tolist()
                batch_t_test = [batch_t_test[x][:50] for x in range(len(batch_t_test))]
            else:
                batch_t_test= batch_t.text[0].tolist()
            outpu = classifier.forward(torch.LongTensor(batch_t_test).to(device),(batch_t.label-1).to(device))
            predictions = outpu[1]
            # no need for backward loss and zero grad
            test_accuracy += f1_score(y_pred=np.argmax((predictions.cpu().detach().numpy()),axis=1),y_true=(batch_t.label-1).cpu().detach().numpy())
            test_loss+=outpu[0].item()
            output.append(predictions)
    avg_test_loss = test_loss/len(val_iter)
    print('val_loss',avg_test_loss)
    final_test_loss.append(avg_test_loss)
    avg_accuracy = test_accuracy/len(val_iter)
    testing_accuracy.append(avg_accuracy)    
    

epoch- 0


In [ ]:
# saving entire model
torch.save(classifier,'tf_classify.pth')

In [ ]:
predictions

In [ ]:
import matplotlib.pyplot as plt
ep = []
for e in range(epoc):
    ep.append(e)
plt.plot(ep,final_loss)
plt.plot(ep,final_test_loss)
plt.savefig('epochs_vs_loss')

In [ ]:
final_loss